Conflict resolve
ThredeX/profesio pull request #124
Opened 2022-03-17 19:39 UTC by Werfmon

2022-03-17 21:26 UTC, JustScreaMy requested changes

2022-03-17 21:26 UTC, JustScreaMy commented on api/auth.js
> +	console.log(req.session.user)
why

2022-03-17 23:07 UTC, Werfmon commented on api/auth.js
> +	console.log(req.session.user)
Yeah, that's a unnecessary.

2022-03-20 15:16 UTC, JustScreaMy requested changes

2022-03-20 15:16 UTC, JustScreaMy commented on utils/userDataReformat.js
> +    console.log(data);
BrUh

2022-03-22 16:55 UTC, JustScreaMy approved these changes

2022-03-22 16:55 UTC, merged