AddingPeople.jsx, theme.js update
ThredeX/profesio pull request #6
Opened 2021-09-25 22:20 UTC by Werfmon

2021-09-27 18:55 UTC, screamy159 approved these changes

2021-10-01 18:40 UTC, screamy159 commented on .gitignore
> +todo.md
Proč je to v .gitignore?

2021-10-01 18:42 UTC, screamy159 requested changes
Nechtěli jsme mít todo veřejné?

2021-10-02 19:53 UTC, Werfmon commented on .gitignore
> +todo.md
Okey

2021-10-03 09:06 UTC, screamy159 approved these changes

2021-10-03 10:22 UTC, Werfmon reviewed
.

2021-10-03 10:30 UTC, merged